#Configuraci\u00f3n IOP
#Mon Apr 06 05:58:48 CST 2026
iop.nombre=TSIGO_RBI
iop.frecuencia=5
api.cid=bMsmOTeAw/fj3Fng/ieoQWBmyeNvqWAX
api.endpoint.device=/device/getDeviceList
api.endpoint.location=/device/getLocationList
api.endpoint.login=/user/login
api.pass=Rb1t3ch2026
api.url=https\://device.vernal.ltd/tagapi
api.user=Rbitech2026
rabbitmq.exchange=change
rabbitmq.pass=1234
rabbitmq.port=5672
rabbitmq.provider=T-SIGO-02
rabbitmq.topic=iop.custom.devicenum
rabbitmq.uri=192.168.1.65
rabbitmq.user=prueba
rabbitmq.vhost=/
redis.frecuencia=60
redis.pass=
redis.port=6379
redis.uri=192.168.1.65
